[workspace]
authors = ["Wm Talcott <wtalcott@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "portfolio-search"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = "25.4.*"
